name: check
on:
  push:
  pull_request:

jobs:
  test:
    name: check ${{ matrix.suite }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - flake8
          - black
          - bandit
          - unittests
    steps:
      - name: Setup python for test ${{ matrix.suite }}
        uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: Install tox
        run: python -m pip install tox
      - name: Run test suite
        run: tox -e ${{ matrix.suite }}